### ISSUE TITLE
Can't execute FlowReg-o

### ISSUE THREAD

**Issue by Dyotson** [IAMLAB-Ryerson/FlowReg#1]
Hi, I tried executing flowreg in google colab, but I always get the same error:

Traceback (most recent call last):
  File "drive/MyDrive/FlowReg/flowreg_o/train.py", line 80, in <module>
    train(args.fixed, args.train, args.validation, args.batch_size, args.epochs, args.checkpoint, args.model_save, args.save_loss, args.alpha)
  File "drive/MyDrive/FlowReg/flowreg_o/train.py", line 51, in train
    model.load_weights(weights)
  File "/tensorflow-1.15.2/python3.7/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.7/keras/engine/network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file read failed: time = Mon Nov  8 21:59:44 2021
, filename = 'drive/MyDrive/FlowReg/', file descriptor = 3, errno = 21, error message = 'Is a directory', buf = 0x7fffcda7f568, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

¿Am I doing something wrong? 

Best regards.

**Comment by sergiumocanu** [comment]
Hi, 

Thanks for bringing this up. The issue is related to a mixup on the input arguments for the `train` function. The fix is in the latest commit https://github.com/IAMLAB-Ryerson/FlowReg/commit/24556d19a77d3eedc7eb3f3ad0a1ba7077167a4e. It should work now. Please let me know if any other issues arise.

**Comment by Dyotson** [comment]
I have modified line per line of the code and I'm still unable to run Flowreg-o, I think you should check your code because I'm still getting errors after modifying a lot of it in flowreg-o (from train.py to data_generator.py)

**Comment by sergiumocanu** [comment]
I've just updated and ran flowreg_o/train.py and it works fine. Please see the latest commit https://github.com/IAMLAB-Ryerson/FlowReg/commit/b3f613f8fc36175b0fd832041c75c7d37508a976. If you have a specific question, please let me know
